export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
export const INIT_BURGER = 'INIT_BURGER'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FAILED_SET_INGREDIENTS = 'FAILED_SET_INGREDIENTS'


export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';


export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT_LINK = 'AUTH_REDIRECT_LINK';